### ISSUE TITLE
[Info] Forked-daapd

### ISSUE THREAD

**Issue by Depechie** [scstraus/home-assistant-config#1]
Hey Sean, more an info question then an issue :)
I also using forked-daapd for my audio streaming across the house.

Can you have some more details on the install? I'm not able to install it on the same machine as Home Assistant because it gives Bonjour exceptions. 

Currently running on other raspberry pi, but after some updates my iOS Remote app is also no longer connecting.

So in general, maybe some more install setup details would be great :)

**Comment by scstraus** [comment]
Originally I installed it as an addon, but recently moved to a standard docker container:
[lscr.io/linuxserver/daapd ](https://docs.linuxserver.io/images/docker-daapd)
The docs there should tell you everything you need to know. I didn't change the docker compose much.

**Comment by Depechie** [comment]
Are you also running the HomeKit integration? I'm getting - mdns: Avahi state change: client collision when I tried running the forked-daapd addon on the same machine as Home Assistant.

**Comment by scstraus** [comment]
No, I don't run homekit. The forked-daapd addon no longer works on HassOS, so I think that's likely your problem. I didn't run into that issue because I run supervised. You'd be best off just using the docker container.

**Comment by Depechie** [comment]
Ok thx for all the info.
I am running supervised too by the way ;)

**Comment by scstraus** [comment]
[This thread has pretty much everything I know about the addon if any of it might help](https://community.home-assistant.io/t/you-need-to-try-forked-daapd-if-you-are-an-itunes-user-airplay-user-or-interested-in-playing-local-music/266407). There are some notes there about avahi. For supervised on debian, the addon was working for me still right up until I switched. Good luck.
